/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas.InternalFrames;

import Dialogs.CrearResponsableCementerio;
import Pantallas.Frames.Principal;
import static Pantallas.Frames.Principal.jDesktopPane1;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;


public class ABMCementerio extends javax.swing.JInternalFrame {

    @Override
    public void dispose() {
        manager.removeKeyEventDispatcher(key);
        super.dispose();
    }
    
    Clases.Cementerio cementerio = new Clases.Cementerio();
    
    JFrame jframe;
    KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
    KeyDispatcher key = new KeyDispatcher();
    
    
    //TECLADO ACCESOS DIRECTOS
    class KeyDispatcher implements KeyEventDispatcher {

        @Override
        public boolean dispatchKeyEvent(KeyEvent e) {
            if (jframe.isActive()) {
                if (e.getID() == KeyEvent.KEY_PRESSED) {
                    if (e.getKeyCode() == 112) {
                        jButton1.doClick();
                    }
                    if (e.getKeyCode() == 113) {
                        jButton2.doClick();
                    }
                    if (e.getKeyCode() == 114) {
                        
                    }
                    if (e.getKeyCode() == 115) {
                        
                    }
                }
            }
            return false;
        }
    }
    
    void cargar(){
        cementerio.Cargar();
        Clases.Class_editar_tabla.main(jTable1, cementerio.datos);
    }
    
    void filtro(String dato){
        cementerio.FiltrarXApeNom(dato);
        
        /*TableColumn b = new TableColumn();
        b.setHeaderValue("Warawara");
        
        jTable1.getColumnModel().addColumn(b);*/
        
        //jTable1.getColumnModel().removeColumn(jTable1.getColumnModel().getColumn(0));
        
        Clases.Class_editar_tabla.main(jTable1, cementerio.datos);
    }
    
    public ABMCementerio() {
        initComponents();
        
        
        cargar();
        
        //Hijack the keyboard manager
        manager.addKeyEventDispatcher(key);
        
        jframe = (JFrame) Principal.jDesktopPane1.getTopLevelAncestor();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setIconifiable(true);
        setTitle("ABM Cementerio");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUM", "BIS", "ZONA", "APE Y NOM DIFUNTO", "APE Y NOM RESP.", "TELEFONO", "DIRECCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName("tabla1"); // NOI18N
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(70);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(80);
        }

        jLabel1.setText("FILTRAR");

        jTextField1.setToolTipText("Filtrar por Nombre del Difunto o Nombre del Responsable");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jButton1.setText("F1 - AGREGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("F2 - MODIFICAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("F3 - COBRAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Ver Responsables");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1093, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        filtro(jTextField1.getText());
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jDesktopPane1.getAllFrames().length != 0) {
            JInternalFrame frame = jDesktopPane1.getAllFrames()[0];
            frame.dispose();
        }
        
        if ("Ver Espacios".equals(jButton4.getText())) {    // AGREGAR RESPONSABLES
            
            CrearResponsableCementerio dialog = new CrearResponsableCementerio(jframe, true, "nuevo");
            String[] responsable_encontrada = dialog.showDialog();
            
            if (responsable_encontrada[0] != null){
                jTextField1.setText(responsable_encontrada[0]);
                filtro(responsable_encontrada[0]);
            }
        } else {                                            // AGREGAR ESPACIOS 
            String[] info = new String[1];
            info[0] = "true";

            ModEspacios frame = new ModEspacios(info);
            frame.setVisible(true);
            jDesktopPane1.add(frame);

            try {
                frame.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1) {
            if (jDesktopPane1.getAllFrames().length != 0) {
                JInternalFrame frame = jDesktopPane1.getAllFrames()[0];
                frame.dispose();
            }

            if ("Ver Espacios".equals(jButton4.getText())) {    // AGREGAR RESPONSABLES

                String dni_responsable = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                
                CrearResponsableCementerio dialog = new CrearResponsableCementerio(jframe, true, dni_responsable);
                String[] responsable_encontrada = dialog.showDialog();

                if (responsable_encontrada[0] != null) {
                    jTextField1.setText(responsable_encontrada[0]);
                    filtro(responsable_encontrada[0]);
                }
            } else {                                            // AGREGAR ESPACIOS 
                String[] info = new String[3];

                info[0] = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                info[1] = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
                info[2] = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();

                ModEspacios frame = new ModEspacios(info);
                frame.setVisible(true);
                jDesktopPane1.add(frame);
                try {
                    frame.setMaximum(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Integer Seleccion = JOptionPane.showOptionDialog(Principal.jDesktopPane1.getSelectedFrame(), "Elija la Opción.", "LinneoAdmin", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Cobrar Inhumación", "Cobrar Cuota", "Cancelar"}, "Si");

        if (Seleccion == 0) {           // Cobrar Inhumación
        
            Integer Seleccion2 = JOptionPane.showOptionDialog(Principal.jDesktopPane1.getSelectedFrame(), "Confirmar pagar Inhumación?", "LinneoAdmin", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Si", "No"}, "Si");

            if (Seleccion2 == 0) {           // SI COBRAR 

            } else if (Seleccion2 == 1) {    // NO COBRAR Y VOLVER A APRETAR EL BOTON
                jButton3.doClick();
            }
        } else if (Seleccion == 1) {    // Cobrar Cuota
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        if("Ver Responsables".equals(jButton4.getText())){
            cementerio.Cargar_responsables();

            /*TableColumn b = new TableColumn();
             b.setHeaderValue("Warawara");
        
             jTable1.getColumnModel().addColumn(b);*/
            jTable1.getColumnModel().removeColumn(jTable1.getColumnModel().getColumn(6));
            jTable1.getColumnModel().removeColumn(jTable1.getColumnModel().getColumn(5));
            jTable1.getColumnModel().removeColumn(jTable1.getColumnModel().getColumn(4));

            jTable1.getColumnModel().getColumn(0).setHeaderValue("DNI");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("APELLIDO Y NOMBRE");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("DIRECCION");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("TELEFONO");

            Clases.Class_editar_tabla.main(jTable1, cementerio.datos);
            
            jButton4.setText("Ver Espacios");
        }else{
            
            TableColumn colum = new TableColumn();
            colum.setHeaderValue("APE Y NOM RESP.");
            jTable1.getColumnModel().addColumn(colum);
            
            TableColumn column = new TableColumn();
            column.setHeaderValue("TELEFONO");
            jTable1.getColumnModel().addColumn(column);
            
            TableColumn columna = new TableColumn();
            columna.setHeaderValue("DIRECCION");
            jTable1.getColumnModel().addColumn(columna);
            
            jTable1.getColumnModel().getColumn(0).setHeaderValue("NUM");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("BIS");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("ZONA");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("APE Y NOM DIFUNTO");
            
            cementerio.Cargar();
            Clases.Class_editar_tabla.main(jTable1, cementerio.datos);
            jButton4.setText("Ver Responsables");
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
