/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogs;

import Pantallas.Frames.Principal;
import static Pantallas.Frames.Principal.df;
import java.awt.Color;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class ModificarBecaCurso extends javax.swing.JDialog {

    JFrame jframe;
    KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
    KeyDispatcher key = new KeyDispatcher();
    
    Clases.Cuotas cuotas = new Clases.Cuotas();
    Clases.TiposPagos tipo_pagos = new Clases.TiposPagos();
    
    BigDecimal monto_anual;
    
    String id_alumno;
    
    @Override
    public void dispose() {
        manager.removeKeyEventDispatcher(key);
        super.dispose(); 
    }
    
    public void showDialog() {
        setVisible(true);
    }
    
    //TECLADO ACCESOS DIRECTOS
    class KeyDispatcher implements KeyEventDispatcher {

        @Override
        public boolean dispatchKeyEvent(KeyEvent e) {
            if (ModificarBecaCurso.this.isActive()) {
                if (e.getKeyCode() == 27) {//ESCAPE
                    jButton2.doClick();
                }

                if (e.getKeyCode() == 112) {
                    jButton1.doClick();
                }
            }
            return false;
        }
    }
    
    void cargar_combo (String id_alumno) {
        jComboBox1.removeAllItems();

        //" - "
        String[][] cant_cursos = Clases.Alumnos.InscripcionesPorAlumno(id_alumno);
        for (int a = 0; a < cant_cursos.length; a++) {
            jComboBox1.addItem(cant_cursos[a][0]);
        }
    }
    
    public ModificarBecaCurso(java.awt.Frame parent, boolean modal, String id) {
        super(parent, modal);
        initComponents();
        
        id_alumno = id;
        
        cargar_combo(id_alumno);
        
        Object[] datos = Clases.Alumnos.Mostrar_Datos(id_alumno);
        
        info_alumno.setText("ID: " + datos[1] + "  -  DNI: " + datos[2] + "  -  APELLIDO Y NOMBRE: " + datos[3].toString().toUpperCase());
        
        //Hijack the keyboard manager
        manager.addKeyEventDispatcher(key);
        jframe = (JFrame) Principal.jDesktopPane1.getTopLevelAncestor();
        
        getRootPane().setBorder( BorderFactory.createLineBorder(Color.RED));
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        beca_hasta_mes = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        beca_hasta_anio = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        beca_desde_mes = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        beca_desde_anio = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        beca_anterior_desde_mes = new javax.swing.JTextField();
        beca_anterior_desde_anio = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        beca_anterior_hasta_mes = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        beca_anterior_hasta_anio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        info_alumno = new javax.swing.JTextField();
        monto_anterior_beca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        monto_nuevo_beca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setText("Modificar Beca");

        jLabel2.setText("Beca anterior");

        jLabel3.setText("Nueva Beca");

        jLabel16.setText("Beca Hasta");

        beca_hasta_mes.setName("numeros"); // NOI18N
        beca_hasta_mes.setNextFocusableComponent(beca_hasta_anio);
        beca_hasta_mes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                beca_hasta_mesKeyReleased(evt);
            }
        });

        jLabel20.setText(" / ");

        beca_hasta_anio.setName("numeros"); // NOI18N
        beca_hasta_anio.setNextFocusableComponent(monto_nuevo_beca);
        beca_hasta_anio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                beca_hasta_anioKeyReleased(evt);
            }
        });

        jLabel17.setText("Beca Desde");

        beca_desde_mes.setName("numeros"); // NOI18N
        beca_desde_mes.setNextFocusableComponent(beca_desde_anio);

        jLabel21.setText(" / ");

        beca_desde_anio.setName("numeros"); // NOI18N
        beca_desde_anio.setNextFocusableComponent(beca_hasta_mes);
        beca_desde_anio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                beca_desde_anioKeyReleased(evt);
            }
        });

        jLabel18.setText("Beca Desde");

        beca_anterior_desde_mes.setEditable(false);
        beca_anterior_desde_mes.setName("numeros"); // NOI18N
        beca_anterior_desde_mes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                beca_anterior_desde_mesKeyReleased(evt);
            }
        });

        beca_anterior_desde_anio.setEditable(false);
        beca_anterior_desde_anio.setName("numeros"); // NOI18N
        beca_anterior_desde_anio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                beca_anterior_desde_anioKeyReleased(evt);
            }
        });

        jLabel22.setText(" / ");

        jLabel19.setText("Beca Hasta");

        beca_anterior_hasta_mes.setEditable(false);
        beca_anterior_hasta_mes.setName("numeros"); // NOI18N
        beca_anterior_hasta_mes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                beca_anterior_hasta_mesKeyReleased(evt);
            }
        });

        jLabel23.setText(" / ");

        beca_anterior_hasta_anio.setEditable(false);
        beca_anterior_hasta_anio.setName("numeros"); // NOI18N
        beca_anterior_hasta_anio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                beca_anterior_hasta_anioKeyReleased(evt);
            }
        });

        jButton1.setText("F1 - GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ESC - SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Curso a modificar");

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel5.setText("Alumno");

        info_alumno.setEditable(false);

        monto_anterior_beca.setEditable(false);

        jLabel6.setText("Monto Beca");

        jLabel7.setText("Monto Beca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 397, Short.MAX_VALUE))
                            .addComponent(info_alumno)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addComponent(beca_anterior_desde_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(beca_anterior_desde_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(monto_anterior_beca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(monto_nuevo_beca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(beca_anterior_hasta_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(beca_anterior_hasta_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(beca_desde_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(beca_desde_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(beca_hasta_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(beca_hasta_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(info_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(beca_anterior_desde_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(beca_anterior_desde_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(monto_anterior_beca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(beca_anterior_hasta_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23)
                        .addComponent(beca_anterior_hasta_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(beca_desde_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(beca_desde_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(beca_hasta_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)
                        .addComponent(beca_hasta_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(monto_nuevo_beca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beca_hasta_mesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_beca_hasta_mesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_beca_hasta_mesKeyReleased

    private void beca_hasta_anioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_beca_hasta_anioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_beca_hasta_anioKeyReleased

    private void beca_desde_anioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_beca_desde_anioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_beca_desde_anioKeyReleased

    private void beca_anterior_desde_mesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_beca_anterior_desde_mesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_beca_anterior_desde_mesKeyReleased

    private void beca_anterior_desde_anioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_beca_anterior_desde_anioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_beca_anterior_desde_anioKeyReleased

    private void beca_anterior_hasta_mesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_beca_anterior_hasta_mesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_beca_anterior_hasta_mesKeyReleased

    private void beca_anterior_hasta_anioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_beca_anterior_hasta_anioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_beca_anterior_hasta_anioKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String detalle_dialog;
        Object[] opciones_dialog;
        Object[] datos = Clases.Alumnos.Mostrar_Datos(id_alumno);
        
        String beca_desde = beca_desde_mes.getText() + "-" + beca_desde_anio.getText();
        String beca_hasta = beca_hasta_mes.getText() + "-" + beca_hasta_anio.getText();
        
        detalle_dialog = "<html><div style='width:300px;'><center><u><b>OPERACION</b></u></center><div></html>\n\n"
                + "<html><u><b>Apellido y Nombre</b></u>: " + datos[3] + ".</html>\n"
                + "<html><u><b>Datos beca</b></u>: " + beca_desde + " hasta " + beca_hasta + ". Con un monto de " + monto_nuevo_beca.getText() +".</html>\n"
                + "¿Desea continuar con la operación?";

        opciones_dialog = new Object[2];
        opciones_dialog[0] = "Guardar";
        opciones_dialog[1] = "Cancelar";
        
        int seleccion = JOptionPane.showOptionDialog(jframe, detalle_dialog, "LinneoAdmin", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones_dialog, "Becas");

        if (seleccion == 0) {
            // GUARDAR PERO SI LA BECA_MONTO ES 0, PAGAR LAS CUOTAS UTILIZANDO EL DESDE Y HASTA
            String seleccionado = jComboBox1.getSelectedItem().toString();
            String id_inscripcion = seleccionado.split("-")[0];
            
            Clases.Alumnos.UpdatearBeca(beca_desde, beca_hasta,new BigDecimal(monto_nuevo_beca.getText().replace(',', '.')), id_inscripcion);
            
            JOptionPane.showMessageDialog(Principal.jDesktopPane1.getSelectedFrame(), "Operación realizada con Exito.", "LinneoAdmin", JOptionPane.INFORMATION_MESSAGE);
            
            
            cargar_combo(id_alumno);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        if (jComboBox1.getItemCount() > 0) {
           
            // TRAER LA BECA
            String seleccionado = jComboBox1.getSelectedItem().toString();
            
            String id_inscripcion = seleccionado.split("-")[0];
            
            String[][] datos = Clases.Alumnos.MostrarBecas(id_inscripcion);
            
            if (!"".equals(datos[0][0])) {
                beca_anterior_desde_mes.setText(datos[0][0].split("-")[0]);     // BECA DESDE
                beca_anterior_desde_anio.setText(datos[0][0].split("-")[1]);    // BECA DESDE
            }
            if (!"".equals(datos[0][1])) {
                beca_anterior_hasta_mes.setText(datos[0][1].split("-")[0]);     // BECA HASTA
                beca_anterior_hasta_anio.setText(datos[0][1].split("-")[1]);    // BECA HASTA
            }
            if (!"".equals(datos[0][2])) {
                monto_anterior_beca.setText(datos[0][2]);                       // BECA MONTO
            }
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarBecaCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarBecaCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarBecaCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarBecaCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarBecaCurso dialog = new ModificarBecaCurso(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField beca_anterior_desde_anio;
    private javax.swing.JTextField beca_anterior_desde_mes;
    private javax.swing.JTextField beca_anterior_hasta_anio;
    private javax.swing.JTextField beca_anterior_hasta_mes;
    private javax.swing.JTextField beca_desde_anio;
    private javax.swing.JTextField beca_desde_mes;
    private javax.swing.JTextField beca_hasta_anio;
    private javax.swing.JTextField beca_hasta_mes;
    private javax.swing.JTextField info_alumno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField monto_anterior_beca;
    private javax.swing.JTextField monto_nuevo_beca;
    // End of variables declaration//GEN-END:variables
}
